Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -1,5 +1,4 @@
-# This workflow will install Python dependencies, run tests and lint with a single version of Python
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
+# This workflow will install Python dependencies, run tests, and lint with a single version of Python
 
 name: Python application
 
@@ -19,16 +18,23 @@ jobs:
 
     steps:
     - uses: actions/checkout@v4
+    
     - name: Set up Python 3.12.6
       uses: actions/setup-python@v3
       with:
         python-version: "3.12.6"
-        
-    - name: Install dependencies with Makefile
+    
+    - name: Check for requirements.txt
       run: |
-        sudo apt-get install make
+        if [ ! -f requirements.txt ]; then
+          echo "Error: requirements.txt not found!"
+          exit 1
+        fi
+    
+    - name: Install dependencies using Makefile
+      run: |
         make install
-        
+    
     - name: Run the Flask server
       run: |
         make run &
@@ -36,13 +42,11 @@ jobs:
 
     - name: Test with pytest
       run: |
-        pytest
+        . venv/bin/activate && pytest
       env:
         FLASK_ENV: testing
 
     - name: Lint with flake8
       run: |
-        # stop the build if there are Python syntax errors or undefined names
-        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
-        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
+        . venv/bin/activate && flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
